import React, { useEffect, useState } from "react";
import api from "../api/axios";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";

const ManagerRevenue = () => {
  const manager = JSON.parse(localStorage.getItem("user"));

  const [users, setUsers] = useState([]);
  const [form, setForm] = useState({});
  const [loadingUserId, setLoadingUserId] = useState(null);

  const today = new Date().toISOString().split("T")[0];

  /* ===============================
     FETCH ASSIGNED USERS
  =============================== */
  const fetchUsers = async () => {
    try {
      const res = await api.get("/users/manager/interns");
      setUsers(res.data);
    } catch (error) {
      console.error("Failed to fetch users:", error);
    }
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  /* ===============================
     HANDLE INPUT CHANGE
  =============================== */
  const handleChange = (userId, field, value) => {
    setForm((prev) => ({
      ...prev,
      [userId]: {
        ...prev[userId],
        [field]: value,
      },
    }));
  };

  /* ===============================
     SUBMIT REVENUE
  =============================== */
  const handleSubmit = async (userId) => {
    const data = form[userId];

    if (!data?.amount || Number(data.amount) <= 0) {
      alert("Enter valid revenue amount");
      return;
    }

    try {
      setLoadingUserId(userId);

      await api.post("/revenue/add", {
        userId,
        amount: Number(data.amount),
        date: data.date || today,
        description: data.description || "",
      });

      alert("✅ Revenue added successfully");

      setForm((prev) => ({
        ...prev,
        [userId]: { amount: "", description: "", date: today },
      }));
    } catch (error) {
      console.error("Revenue update failed:", error);
      alert("Failed to add revenue");
    } finally {
      setLoadingUserId(null);
    }
  };

  /* ===============================
     UI
  =============================== */
  return (
    <div className="flex min-h-screen bg-gradient-to-br from-orange-50 via-amber-50 to-gray-100">
      <Sidebar />

      <div className="flex-1 md:ml-64 px-4 sm:px-6 py-6">
        <Navbar user={manager} />

        {/* HEADER */}
        <section className="relative mt-6 overflow-hidden rounded-[28px]
          bg-gradient-to-r from-orange-500 via-amber-500 to-orange-400
          text-white p-6 sm:p-8 shadow-2xl"
        >
          <h1 className="text-2xl sm:text-3xl font-bold">
            Daily Revenue Update
          </h1>
          <p className="text-sm text-white/85 mt-2">
            Record revenue generated by your assigned team members.
          </p>
        </section>

        {/* CONTENT */}
        {users.length === 0 ? (
          <div className="mt-10 text-gray-500">
            No users assigned to you.
          </div>
        ) : (
          <>
            {/* DESKTOP TABLE */}
           <div className="hidden lg:block mt-10 bg-white border rounded-2xl shadow-sm
  overflow-x-auto max-w-6xl mx-auto"
>
  <table className="w-full text-sm border-collapse">
    <thead className="bg-gray-50 text-gray-600">
      <tr>
        <th className="p-4 text-left">Employee</th>
        <th className="p-4 text-center">Role</th>
        <th className="p-4 text-center">Date</th>
        <th className="p-4 text-center">Amount (₹)</th>
        <th className="p-4 text-center">Description</th>
        <th className="p-4 text-center">Action</th>
      </tr>
    </thead>

    <tbody>
      {users.map((u) => (
        <tr
          key={u._id}
          className="border-t hover:bg-gray-50 align-middle"
        >
          {/* EMPLOYEE */}
          <td className="p-4 font-medium text-left whitespace-nowrap">
            {u.name}
          </td>

          {/* ROLE */}
          <td className="p-4 text-center capitalize">
            {u.role}
          </td>

          {/* DATE */}
          <td className="p-4 text-center">
            <input
              type="date"
              value={form[u._id]?.date || today}
              onChange={(e) =>
                handleChange(u._id, "date", e.target.value)
              }
              className="border rounded-lg px-3 py-2 text-center w-40"
            />
          </td>

          {/* AMOUNT */}
          <td className="p-4 text-center">
            <input
              type="number"
              value={form[u._id]?.amount || ""}
              onChange={(e) =>
                handleChange(u._id, "amount", e.target.value)
              }
              className="border rounded-lg px-3 py-2 text-center w-32"
            />
          </td>

          {/* DESCRIPTION */}
          <td className="p-4 text-center">
            <input
              type="text"
              value={form[u._id]?.description || ""}
              onChange={(e) =>
                handleChange(u._id, "description", e.target.value)
              }
              className="border rounded-lg px-3 py-2 w-64"
            />
          </td>

          {/* ACTION */}
          <td className="p-4 text-center">
            <button
              onClick={() => handleSubmit(u._id)}
              disabled={loadingUserId === u._id}
              className="bg-orange-600 hover:bg-orange-700
                text-white px-5 py-2 rounded-xl"
            >
              {loadingUserId === u._id ? "Saving…" : "Add"}
            </button>
          </td>
        </tr>
      ))}
    </tbody>
  </table>
</div>


            {/* MOBILE CARDS */}
            <div className="lg:hidden mt-10 space-y-4">
              {users.map((u) => (
                <div
                  key={u._id}
                  className="bg-white border rounded-2xl shadow-sm p-5"
                >
                  <p className="font-semibold">{u.name}</p>
                  <p className="text-sm text-gray-500 capitalize mb-3">
                    {u.role}
                  </p>

                  <div className="grid grid-cols-2 gap-3">
                    <input
                      type="date"
                      value={form[u._id]?.date || today}
                      onChange={(e) =>
                        handleChange(u._id, "date", e.target.value)
                      }
                      className="border rounded-lg px-3 py-2"
                    />

                    <input
                      type="number"
                      value={form[u._id]?.amount || ""}
                      onChange={(e) =>
                        handleChange(u._id, "amount", e.target.value)
                      }
                      className="border rounded-lg px-3 py-2"
                    />

                    <input
                      type="text"
                      value={form[u._id]?.description || ""}
                      onChange={(e) =>
                        handleChange(u._id, "description", e.target.value)
                      }
                      className="border rounded-lg px-3 py-2 col-span-2"
                    />
                  </div>

                  <button
                    onClick={() => handleSubmit(u._id)}
                    disabled={loadingUserId === u._id}
                    className="mt-4 w-full bg-orange-600 hover:bg-orange-700
                      text-white py-2.5 rounded-xl"
                  >
                    {loadingUserId === u._id ? "Saving…" : "Add Revenue"}
                  </button>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default ManagerRevenue;
